repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements

-   repo: local
    hooks:
    -   id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        args: [--config=pyproject.toml]

    -   id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]
        args: [--config-file=pyproject.toml]

    -   id: ruff
        name: ruff
        entry: poetry run ruff check
        language: system
        types: [python]
        args: [--fix, --config=pyproject.toml]

    -   id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        types: [python]
